@HOTCH_ID = 690ab7ea8bc87b5ecf79352c


### Request 1: Create a pet
POST http://localhost:3000/pets HTTP/1.1
content-type: application/json

{
    "name": "Hotchner",
    "species": "Canine",
    "breed": "Golden Retriever/Lab Mix",
    "sex": "Male",
    "dob": "10-20-20",
    "weight": 90
}


### Request 2: Create another pet
POST http://localhost:3000/pets HTTP/1.1
content-type: application/json

{
    "name": "Oakley",
    "species": "Canine",
    "breed": "Collie/Hound Mix",
    "sex": "Female",
    "dob": "03-01-15",
    "weight": 65
}

### Request 3: Retrieve all
GET http://localhost:3000/pets HTTP/1.1


### Request 4: Retrieve by ID
GET  http://localhost:3000/pets/{{HOTCH_ID}} HTTP/1.1


### Request 4: Update Hotchner with weight 85
PUT http://localhost:3000/pets/{{HOTCH_ID}} HTTP/1.1
content-type: application/json

{
    "name": "Hotchner",
    "species": "Canine",
    "breed": "Golden Retriever/Lab Mix",
    "sex": "Male",
    "dob": "10-20-20",
    "weight": 85
}


### Request 19: Delete Hotchner
DELETE http://localhost:3000/pets/{{HOTCH_ID}} HTTP/1.1